name: cron

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  cron:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run Cron
        run: |
          npm install
          npm start
      - name: Push Github
        run: |
          git config --global user.name "haesoo-y"
          git config --global user.email "haesoo9410@gmail.com"
          git pull origin main
          git add .
          git commit -m ":memo: 리드미 업데이트" || exit 0
          git push
